### ISSUE TITLE
Error on Emulator.create_device in 0.6.1

### ISSUE THREAD

**Issue by virgesmith** [disruptive-technologies/python-client#76]
Hi DT developers, 

This code

```
import os
import disruptive as dt
from dotenv import load_dotenv
load_dotenv()

_KEY_ID = os.getenv('DT_SVC_KEY', '')
_SECRET = os.getenv('DT_SVC_SECRET', '')
_EMAIL = os.getenv('DT_SVC_EMAIL', '')
_PROJECT_ID = os.getenv('DT_PROJECT', '')

dt.default_auth = dt.Auth.service_account(_KEY_ID, _SECRET, _EMAIL)

res = dt.Emulator.create_device(_PROJECT_ID, dt.Device.HUMIDITY, display_name="TEST")

print(res)
```

Results in

```
Traceback (most recent call last):
  File "mcve.py", line 13, in <module>
    res = dt.Emulator.create_device(_PROJECT_ID, dt.Device.HUMIDITY, display_name="TEST")
  File "/mnt/data/dev/Friarswood/.venv-Friarswood-focal/lib/python3.8/site-packages/disruptive/resources/emulator.py", line 76, in create_device
    return Device(dtrequests.DTRequest.post(
  File "/mnt/data/dev/Friarswood/.venv-Friarswood-focal/lib/python3.8/site-packages/disruptive/resources/device.py", line 74, in __init__
    self.product_number: str = device['productNumber']
KeyError: 'productNumber'
```

I think this might be related to #75, but there doesnt appear to be any change to how you construct an emulator (I tried passing `product_number` arg but this didnt work.

Note also that the device *does* get created despite the error.
 
Cheers
Andrew

**Comment by jhgjeraker** [comment]
Good day!

Good catch. You are completely correct.
This is related to #75 where we introduced product numbers for our devices. When fetching a device through our main REST API a device will include a product number. For emulated devices, this is an empty string. However, when creating an emulated device, the emulator API is used, which does not return a product number. This was overlooked. My mistake.

I am working on a fix as we speak and will update this thread when it has been published.

**Comment by jhgjeraker** [comment]
I have issued an update (v0.6.2) which should fix the issue. 
Please update your package and try your example again.

**Comment by virgesmith** [comment]
@jhgjeraker yes 0.6.2 fixes, thanks for extremely swift resolution!
